name: tauritest1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: rust
        uses: dtolnay/rust-toolchain@stable

      - name: dependencies
        run: npm i

      - name: build
        run: npm run tauri build -- --debug

      - name: timestamp
        id: timestamp
        run: echo "value=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.timestamp.outputs.value }}
          path: src-tauri/target/debug/*.exe