name: action01

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: rust
        uses: dtolnay/rust-toolchain@stable

      - name: rust cache
        uses: Swatinem/rust-cache@v2

      - name: dependencies
        run: npm ci

      - name: build
        run: npm run tauri build

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          path: src-tauri/target/release/**